=== augustpalo/GS1-LM/DTD/DTD5/lol.dtd
<!ELEMENT panel (nombre,vuelo+,fecha)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT vuelo (diario?,origen,destino,horaS,horaLL)>
<!ATTLIST vuelo codigo NMTOKEN #REQUIRED>
<!ATTLIST vuelo estado NMTOKEN #REQUIRED>
<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT horaS (#PCDATA)>
<!ELEMENT horaLL (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== augustpalo/GS1-LM/DTD/DTD5/ejemplo.xml
<?xml version='1.0' encoding='utf-8' standalone="no"?>
<!DOCTYPE panel SYSTEM "lol.dtd">

<panel>
    <nombre>Aeropuerto JFK</nombre>
    <vuelo codigo="V22" estado="E">
        <diario />
        <origen>New york</origen>
        <destino>Chicago</destino>
        <horaS>9:30</horaS>
        <horaLL>11:30</horaLL>
    </vuelo>
    <vuelo codigo="V23" estado="C">
        <origen>New york</origen>
        <destino>Miami</destino>
        <horaS>10:15</horaS>
        <horaLL>11:15</horaLL>
    </vuelo>
    <fecha>20/12/2013</fecha>
</panel>
